> # 05.利用numpy.array进行一些常用基础操作

In [4]:
import numpy as np

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

+ ### 基本属性

In [15]:
x.ndim # 返回元素的维度

1

In [17]:
X.ndim

2

In [21]:
x.shape # 返回数组的元组(几行几列)

(10,)

In [22]:
X.shape

(3, 5)

In [25]:
x.size # 元素个数

10

In [27]:
X.size

15

+ ### 数据访问

In [29]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[5]

5

In [36]:
X[0][0] # 不推荐这么访问

0

In [39]:
X[2, 2] # 推荐这样访问

12

In [42]:
x[1:5] # 访问0~5的元素(不含5)

array([1, 2, 3, 4])

In [45]:
x[:5] # 开头不写，默认从0开始访问

array([0, 1, 2, 3, 4])

In [48]:
x[5:] # 结尾不写，默认到最后

array([5, 6, 7, 8, 9])

In [58]:
x[::2] # 从头(第1个参数)访问到尾(第2个参数)，步长为2(第3个参数)

array([0, 2, 4, 6, 8])

In [52]:
x[::-1] # 从头(第一个参数)访问到尾(第二个参数)，步长为-1,相当于倒序访问

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
X[:2, :3] # 访问前两行(2表示行作为从开始位置到2，  3表示从开始位置到第3列)

array([[0, 1, 2],
       [5, 6, 7]])

In [63]:
X[:2][:3] # 这样访问是不能正常访问前2行前3列地，访问地地是先取前2行，再从取地结果中取前3行，因为只有两行，所以前两行内容全部打印

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
X[:2, ::2] # 访问前两行，间隔为2

array([[0, 2, 4],
       [5, 7, 9]])

In [68]:
X[::-1, ::-1] # 行和列都倒着访问，相当于转置了

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [69]:
X[0] # 访问第一行

array([0, 1, 2, 3, 4])

In [70]:
X[0 ,:] # 访问第一行，写上第二个参数

array([0, 1, 2, 3, 4])

In [72]:
X[:, 0] # 只取第一列

array([ 0,  5, 10])

In [75]:
subX = X[:2, :3] #取两行3列作为子矩阵
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [81]:
subX[0][0] = 100 # 取子矩阵，通过应用取地，所以子矩阵修改会影响父矩阵
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [82]:
X # 子矩阵修改影响父矩阵

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [84]:
X[0][0] = 0 # 修改父矩阵也影响子矩阵
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [89]:
subX2 = X[:2, :3].copy()  # 获取真正的子矩阵，并且父子矩阵修改互不影响
subX2

array([[0, 1, 2],
       [5, 6, 7]])

In [92]:
subX2[0][0] = 100 
subX2

array([[100,   1,   2],
       [  5,   6,   7]])

In [95]:
X  # copy后生成的子矩阵修改不影响父矩阵

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

+ ### Reshape 重新调整数组的维度

In [97]:
x.shape

(10,)

In [100]:
x.ndim

1

In [106]:
A = x.reshape(2, 5)   # 把10个元素的一维数组，变成2行5列的二维数组
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
B = x.reshape(1, 10) # 调整成1行10列的二维数组(没错，就是二维数组)，注意看中括号的个数
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [112]:
B.ndim  # 维度是2，说明是二维数组，印证了上面的结论

2

In [120]:
x.reshape(5 ,-1) # 改为10行x列(-1表示不在乎有多少列)的数组,5行是必须地

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [122]:
x.reshape(-1 , 2) # 改为x行(-1表示不在乎有多少行)2列的数组，2列是必须地

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [124]:
x.reshape(-1 , 5) # 改为x行(-1表示不在乎有多少行)5列的数组，5列是必须地，但是前提一定要正整除！！

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])