# 03 Numpy.array 基础

In [2]:
import numpy

In [4]:
numpy.__version__

'1.12.1'

In [6]:
import numpy as np

In [8]:
np.__version__

'1.12.1'

## Python List的特点

In [10]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
L[5]

'Liang Shan Guang'

In [18]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [19]:
L[5] = "Liang Shan Guang"
L

[0, 1, 2, 3, 4, 'Liang Shan Guang', 6, 7, 8, 9]

In [22]:
import array

In [30]:
arr = array.array('i', [i for i in range(10)]) # 强制指定数组类型，下面不能再赋字符串了

In [31]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5] = 100

In [34]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [38]:
arr[5] = "wang" # 这时的数组只能赋整型了，再赋字符串就会报错了

TypeError: an integer is required (got type str)

In [40]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

## numpy.array 要比python自带地array好很多

In [42]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [47]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [50]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [53]:
nparr.dtype # 查看数组中的数据存储类型

dtype('int64')

In [56]:
nparr[5] = 5.0 # 会自动强制转换地
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
nparr[3] = 3.64 # 会自动舍去小数点后面的部分
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
nparr.dtype

dtype('int64')

In [65]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([ 1.,  2.,  3.])

In [66]:
nparr2.dtype

dtype('float64')