# 06 拼接与拆分

## 一、拼接

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [3]:
y = np.array([3, 2, 1])
y

array([3, 2, 1])

In [4]:
np.concatenate([x, y]) # 拼接向量x和y

array([1, 2, 3, 3, 2, 1])

In [5]:
z = np.array([6, 66, 666])
z

array([  6,  66, 666])

In [6]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1,   6,  66, 666])

In [7]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([A, A], axis = 1) # axis = 0表示沿着行的方向↓拼接，默认为0，见上一条命令；axis = 1表示沿着列→拼接，即本次的结果

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

 > concatenate拼接的两个矩阵需要满足的条件
 + 维度相等(`数组.ndim`相等)
 + 拼接方向上长度相等的矩阵

In [10]:
np.concatenate([A, z])  # concatenate只能拼接维度相等(ndim相同)、拼接方向上长度相等的矩阵

ValueError: all the input arrays must have same number of dimensions

In [47]:
z.reshape(1, -1).shape  # 变成1行3列的的二维数组了

(1, 3)

In [49]:
z.shape # 原来只是一个有3个元素的一维数组

(3,)

In [11]:
np.concatenate([A, z.reshape(1, -1)])  # concatenate只能处理维度一样的矩阵,要想处理只能先转变为二维矩阵,reshape使用见上一节

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  66, 666]])

In [12]:
A2 = np.concatenate([A, z.reshape(1, -1)])  # concatenate只能处理维度一样地矩阵,要想处理只能先转变为二维矩阵,reshape使用见上一节
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  66, 666]])

In [13]:
A  # 可见拼接结果是一个新的值，因为A并没有变

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
A3 = np.vstack([A, z])  # 智能地进行垂直方向↓(vertical)进行堆叠(不用再reshape了) 。 vstack要求列数相同
A3

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  66, 666]])

In [15]:
B = np.full([2, 2], 100)
B

array([[100, 100],
       [100, 100]])

In [16]:
np.hstack([A, B])  # 将A和B在水平方向→(horizontal)上进行堆叠(不用再reshape了)。hstack要求行数相同

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 二、拆分

In [17]:
x = np.arange(10) # 生成[0, 10)的元素，起点默认为0， 步长默认为1，默认不包含终点数字
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.split(x, [3, 7])  # 第二个参数是要分割的数组，第二个参数是分割点

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [19]:
x1, x2, x3 = np.split(x, [3, 7])  # 第二个参数是要分割的数组，第二个参数是分割点(索引数组)

In [20]:
x1

array([0, 1, 2])

In [21]:
x2

array([3, 4, 5, 6])

In [22]:
x3

array([7, 8, 9])

In [23]:
x1, x2 = np.split(x, [6])

In [24]:
x1

array([0, 1, 2, 3, 4, 5])

In [25]:
x2

array([6, 7, 8, 9])

In [26]:
A = np.arange(16).reshape(4, 4) # 先生成16个元素的一维数组再转换成4*4的矩阵
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
A1, A2 = np.split(A,[2])  # 基于第一维进行分割，2实际上是行号。可用vsplit代替

In [28]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
A1, A2 = np.split(A,[2], axis = 1)  # 基于第一维进行分割，2实际上是列号，因为axis = 1表示纵向切分。可用hsplit代替

In [31]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [32]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [33]:
upper, lower = np.vsplit(A, [2])  ## 沿着垂直方向的索引(第几行)进行拆分，分上上下两部分(上下是vertical方向)，2是行号，所以叫vsplit

In [34]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
left, right = np.hsplit(A, [2]) # 沿着水平方向的索引(第几列)进行拆分，分成左右两部分(左右是horizontal方向)，2是列号，所以叫hsplit

In [37]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [38]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## 在机器学习中的应用(拆分特征和结果，结果一般在最后一列)

In [39]:
data = np.arange(16).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
x, y = np.hsplit(data, [-1]) # 水平分割分左右，-1代表只把最后一列分出来

In [41]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [42]:
y   # y实际就是处理结果(特征向量的最后一列)

array([[ 3],
       [ 7],
       [11],
       [15]])

In [43]:
y[:, 0] # 抽出所有的行和第0列，相当于转置y了，成为一个一维数组(向量)

array([ 3,  7, 11, 15])