# 聚合操作

In [2]:
import numpy as np

In [4]:
L = np.random.random(100)
L

array([ 0.63887634,  0.35223505,  0.22536245,  0.22927974,  0.54591735,
        0.04803576,  0.681302  ,  0.97771345,  0.25922196,  0.6378412 ,
        0.05423964,  0.41962974,  0.59911327,  0.04683758,  0.12505498,
        0.70019644,  0.80441551,  0.31266538,  0.34631703,  0.54712781,
        0.09433605,  0.61481345,  0.53609996,  0.86125847,  0.73258809,
        0.28647909,  0.84310738,  0.18473059,  0.65071228,  0.40652579,
        0.31241333,  0.54490466,  0.3252323 ,  0.08207719,  0.08672767,
        0.27819405,  0.84369013,  0.67503273,  0.37182507,  0.60311559,
        0.32498608,  0.70295542,  0.40411346,  0.71166807,  0.89878553,
        0.84266199,  0.34141528,  0.18968278,  0.61050794,  0.37215183,
        0.85766594,  0.16185218,  0.45669429,  0.59525382,  0.30749706,
        0.41806831,  0.61567742,  0.67749548,  0.54010829,  0.04769625,
        0.07244345,  0.24649305,  0.99243801,  0.6476653 ,  0.27174724,
        0.44355766,  0.26465264,  0.39245519,  0.52819085,  0.76

In [6]:
sum(L)

48.807715829320522

In [9]:
np.sum(L) # 效率要比系统自带地sum高很多

48.807715829320514

In [13]:
big_array = np.random.rand(1000000)
%timeit sum(big_array) # 和下面的方法的效率差了100多倍
%timeit np.sum(big_array)

10 loops, best of 3: 115 ms per loop
1000 loops, best of 3: 723 µs per loop


In [15]:
np.max(big_array)

0.99999972284945604

In [17]:
np.min(big_array)

6.8567434130528682e-07

In [21]:
big_array.min()  # 用面向对象地方法求最大和最小值

6.8567434130528682e-07

In [22]:
big_array.max()

0.99999972284945604

In [24]:
X = np.arange(16).reshape(4, -1)  # 有4行就行，-1代表列数自动分配
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.sum(X) # 求所有元素的和

120

In [29]:
np.sum(X, axis=0)  # 求每列元素的和(沿着行的方向)组成一个行向量

array([24, 28, 32, 36])

In [32]:
np.sum(X, axis=1)  # 求每行元素的和(沿着列的方向)组成一个列向量

array([ 6, 22, 38, 54])

In [34]:
np.prod(X)  # X中所有元素的乘积

0

In [36]:
np.prod(X + 1)

20922789888000

In [38]:
np.median(X) # 中位数

7.5

In [40]:
v = np.array([1, 1, 2, 2, 10])
v

array([ 1,  1,  2,  2, 10])

In [43]:
np.mean(v)  # 平均值

3.2000000000000002

In [46]:
np.median(v) # 中位数，能更好地描述样本

2.0

In [49]:
np.percentile(big_array, q = 50) # 矩阵big_array中50%的值都是小于下面的结果地,不写q默认也是50

0.49893246220088033

In [51]:
np.percentile(big_array, q = 100) # 矩阵big_array中100%的值都是小于下面的结果地

0.99999972284945604

In [54]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q = percent))

6.85674341305e-07
0.249347213266
0.498932462201
0.749311031619
0.999999722849


In [55]:
np.var(big_array)  # 数组的方差

0.083348722076812751

In [57]:
np.std(big_array) # 标准差

0.28870178744997882

In [59]:
x = np.random.normal(0, 1, size=1000000)  # 产生100万个均值为0，标准差为1的随机数

In [62]:
np.mean(x) # 均值非常接近0了

0.00039331062524494009

In [64]:
np.std(x) # 标准差，果然非常接近1

1.0003192662733769