# numpy.array进行矩阵运算

给定一个向量，让想两种的每一个数乘以2 <br>
a = (0, 1, 2) <br> 
a*2 = (0, 2, 4) <br>

In [2]:
n = 10
L = [i for i in range(n)]

In [4]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
2 * L  # 这种方式并不能达到效果

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
n = 1000000
L = [i for i in range(n)]

In [15]:
%%time
A = []
for e in L:       # 用传统的for循环很慢
    A.append(2*e)

CPU times: user 296 ms, sys: 36.4 ms, total: 333 ms
Wall time: 354 ms


In [17]:
%%time
A = [2*e for e in L] # 用生成表达式明显快很多

CPU times: user 136 ms, sys: 43 ms, total: 179 ms
Wall time: 237 ms


In [22]:
import numpy as np
L = np.arange(n)

In [26]:
%%time
A = np.array(2*e for e in L)  # 用numpy生成数组的速度明显快多了

CPU times: user 38 µs, sys: 1 µs, total: 39 µs
Wall time: 50.1 µs


In [30]:
%%time
A = 2 * L  # numpy中的*2正是我们想要的结果，而且效果要快地多

CPU times: user 3.6 ms, sys: 2.18 ms, total: 5.79 ms
Wall time: 3.27 ms


In [32]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

## Universla Functions(数字和矩阵之间的运算)

In [34]:
x = np.arange(1, 16).reshape((3, 5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
x + 1   # 矩阵加法

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [39]:
x - 1 # 矩阵减法

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
x * 2 # 乘法

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [43]:
x / 2  # 浮点数除法

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5]])

In [45]:
x // 2 # 整数除法

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [47]:
1 / x # 取倒数

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ],
       [ 0.09090909,  0.08333333,  0.07692308,  0.07142857,  0.06666667]])

In [49]:
np.abs(x)  # 求绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [52]:
np.sin(x) # 正弦函数

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [54]:
np.cos(x) # 求余弦

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [56]:
np.tan(x) # 余弦

array([[  1.55740772e+00,  -2.18503986e+00,  -1.42546543e-01,
          1.15782128e+00,  -3.38051501e+00],
       [ -2.91006191e-01,   8.71447983e-01,  -6.79971146e+00,
         -4.52315659e-01,   6.48360827e-01],
       [ -2.25950846e+02,  -6.35859929e-01,   4.63021133e-01,
          7.24460662e+00,  -8.55993401e-01]])

In [58]:
np.exp(x) # 求e的x次方

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
          5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
          8.10308393e+03,   2.20264658e+04],
       [  5.98741417e+04,   1.62754791e+05,   4.42413392e+05,
          1.20260428e+06,   3.26901737e+06]])

In [60]:
np.power(3, x) # 求3的x次方， 等效于3**x

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [62]:
3**x

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [64]:
np.log(x) # 取对数值

array([[ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791],
       [ 1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509],
       [ 2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ]])

In [66]:
np.log2(x) #以2为底的对数

array([[ 0.        ,  1.        ,  1.5849625 ,  2.        ,  2.32192809],
       [ 2.5849625 ,  2.80735492,  3.        ,  3.169925  ,  3.32192809],
       [ 3.45943162,  3.5849625 ,  3.70043972,  3.80735492,  3.9068906 ]])

In [68]:
np.log10(x) #以10为底的对数

array([[ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ],
       [ 0.77815125,  0.84509804,  0.90308999,  0.95424251,  1.        ],
       [ 1.04139269,  1.07918125,  1.11394335,  1.14612804,  1.17609126]])

## 矩阵和矩阵之间的运算