# Sklearn中的Scaler使用

In [21]:
import numpy as np
from sklearn import datasets

In [22]:
iris = datasets.load_iris()

In [23]:
X = iris.data
y = iris.target

In [24]:
X[:10, :] # 前10行

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target)

# StandardScaler

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
 standardScaler = StandardScaler()

In [28]:
standardScaler.fit(X_train)  # 归一化

StandardScaler(copy=True, with_mean=True, with_std=True)

In [29]:
standardScaler.mean_

array([ 5.84910714,  3.04017857,  3.83482143,  1.23125   ])

In [30]:
standardScaler.std_

/Users/liangshanguang/anaconda/lib/python3.6/site-packages/sklearn/utils/deprecation.py:70: DeprecationWarning: Function std_ is deprecated; Attribute ``std_`` will be removed in 0.19. Use ``scale_`` instead
  warnings.warn(msg, category=DeprecationWarning)


array([ 0.84915878,  0.41650326,  1.76845927,  0.77171322])

In [31]:
standardScaler.scale_ # std建议用scale替换

array([ 0.84915878,  0.41650326,  1.76845927,  0.77171322])

In [32]:
standardScaler.transform(X_train) # 对整个矩阵进行归一化，不会改变X_train

array([[ 1.59086014,  1.34409854,  1.28087687,  1.64406928],
       [ 0.41322408,  0.86391023,  0.88505209,  1.38490565],
       [-1.1177028 , -0.0964664 , -1.37680379, -1.33631247],
       [-0.76441198,  0.86391023, -1.37680379, -1.33631247],
       [ 1.00204211,  0.14362775,  0.31958812,  0.21866931],
       [ 0.53098769,  0.86391023,  0.99814488,  1.51448747],
       [ 1.00204211,  0.14362775,  0.48922731,  0.34825113],
       [-0.05783034, -1.05684303,  0.09340253, -0.04049432],
       [-0.52888477,  2.06438101, -1.2071646 , -1.07714884],
       [-0.88217559, -1.29693719, -0.47206144, -0.17007613],
       [ 0.29546048, -0.0964664 ,  0.43268091,  0.21866931],
       [-1.1177028 , -1.53703135, -0.30242225, -0.29965795],
       [-0.99993919,  1.10400438, -1.43335019, -1.20673065],
       [-0.64664837,  1.5841927 , -1.3202574 , -1.33631247],
       [ 0.7665149 , -0.0964664 ,  1.11123768,  1.25532384],
       [ 0.53098769, -0.33656056,  0.99814488,  0.73699657],
       [ 1.23756933,  0.

In [33]:
X_train = standardScaler.transform(X_train) # 对整个矩阵进行归一化，不会改变X_train,所以需要赋值

In [34]:
X_test_standard = standardScaler.transform(X_test)

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [37]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [38]:
knn_clf.score(X_test_standard, y_test) # 获取计算地准确率。训练数据集和测试数据集必须都进行归一化(transform)操作

0.97368421052631582