# Fancy Indexing

In [31]:
import numpy as np

In [32]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
np.random.shuffle(x)
x

array([ 3,  1,  7, 14, 10,  9,  4, 13, 15,  5, 12,  2,  8,  6, 11,  0])

In [34]:
x[3]

14

In [35]:
x[3:9] # 索引一个范围

array([14, 10,  9,  4, 13, 15])

In [36]:
x[3:9:2] # 索引范围，加上一个步长，两个扫一个

array([14,  9, 13])

In [37]:
indexes = [3, 5, 8]
x[indexes]

array([14,  9, 15])

In [38]:
indexes = np.array([
    [0, 2],
    [1, 3]
])
x[indexes]  # 生辰对应索引组成的二维数组

array([[ 3,  7],
       [ 1, 14]])

In [39]:
X = x.reshape(4, -1)  # 生成4行的矩阵，列自适应
X

array([[ 3,  1,  7, 14],
       [10,  9,  4, 13],
       [15,  5, 12,  2],
       [ 8,  6, 11,  0]])

In [43]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col] # 分别获取0行1列，1行2列，2行3列的元素

array([1, 4, 2])

In [45]:
X[0, col] # 获取坐标为(0, 1)、(0, 2)、(0, 3) 对应的数据

array([ 1,  7, 14])

In [46]:
X[:2, col] # 前两行(:前无东西默认是整行)列坐标为1，2，3的元素

array([[ 1,  7, 14],
       [ 9,  4, 13]])

In [48]:
col = [True, False, True, True] # 为True表示取对应列的元素

In [49]:
X[1:3, col] # 取1-3行感兴趣的列

array([[10,  4, 13],
       [15, 12,  2]])

# numpy.array的批量比较

In [51]:
x

array([ 3,  1,  7, 14, 10,  9,  4, 13, 15,  5, 12,  2,  8,  6, 11,  0])

In [52]:
x < 3 # 列出数组中元素与3比较的情况，大于3为False， 小于3位True

array([False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True], dtype=bool)

In [53]:
x > 3 # 列出数组中元素与3比较的情况，大于3为True， 小于3位False

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False], dtype=bool)

In [54]:
x <= 3

array([ True,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True], dtype=bool)

In [55]:
x >= 3

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False], dtype=bool)

In [56]:
x != 3

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [61]:
2 * x == 24 - 4 * x  # 注意有两个等号，解出x = 6, 所以下标为6的元素为True

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [62]:
X

array([[ 3,  1,  7, 14],
       [10,  9,  4, 13],
       [15,  5, 12,  2],
       [ 8,  6, 11,  0]])

In [64]:
X < 6 # 小于6的元素为True

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False,  True, False,  True],
       [False, False, False,  True]], dtype=bool)

In [65]:
x

array([ 3,  1,  7, 14, 10,  9,  4, 13, 15,  5, 12,  2,  8,  6, 11,  0])

In [66]:
np.sum(x <= 4)  # 数组中<=4的元素有几个

5

In [67]:
np.count_nonzero(x <= 3) # <=3 但是非零的数组元素个数

4

In [68]:
np.any(x == 0) # 数组中有任意一个元素等于0就返回True

True

In [69]:
np.any(x < 0) # 数组中是否有任何小于0的元素

False

In [70]:
np.all(x >= 0) # 是否数组中所有元素都 >= 0

True

In [71]:
X

array([[ 3,  1,  7, 14],
       [10,  9,  4, 13],
       [15,  5, 12,  2],
       [ 8,  6, 11,  0]])

In [75]:
np.sum(X % 2 == 0) # 一共几个偶数

8

In [76]:
np.sum(X % 2 == 0, axis=1) #沿着列的方向(每一行) 各有几个偶数

array([1, 2, 2, 3])

In [77]:
np.sum(X % 2 == 0, axis=0) #沿着行的方向(每一列) 各有几个偶数

array([2, 1, 2, 3])

In [78]:
np.all(X>0, axis=1) # #沿着列的方向(每一行)是否都大于0

array([ True,  True,  True, False], dtype=bool)

In [79]:
x

array([ 3,  1,  7, 14, 10,  9,  4, 13, 15,  5, 12,  2,  8,  6, 11,  0])

In [80]:
np.sum((x>3)&(x<10))  # 3 < x < 10的元素个数，注意只有一个&

6

In [82]:
np.sum((x % 2 == 0)| (x > 10)) # 偶数或者>10的元素个数

11

In [84]:
np.sum(~(x==0)) # x不等于0的元素个数

15

In [86]:
x[x < 5] # 小于5的元素列表

array([3, 1, 4, 2, 0])

In [88]:
x[ x%2==0] # 所有的偶数

array([14, 10,  4, 12,  2,  8,  6,  0])