# 04 numpy.array的其他方法

In [3]:
import numpy as np

In [10]:
np.zeros(10) # 默认是创建浮点数组

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros(10).dtype

dtype('float64')

In [13]:
np.zeros(10, dtype=int) # 人为指定去创建整型数组

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.zeros((3, 5)) # 传入元组来初始化

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [22]:
np.zeros(shape = (3, 5), dtype=int) # 传入元组来初始化,指定为整型数组

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.ones(10) # 初始化为全1的数组

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
np.ones((3,5)) # 传入元组指定行和列

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [28]:
np.full((3, 5), 666)  # 用指定元素来初始化一个元组

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [31]:
np.full((3, 5), 666.6)  # 用指定元素来初始化一个元组，自动根据元素类型来确定整个数组的类型

array([[ 666.6,  666.6,  666.6,  666.6,  666.6],
       [ 666.6,  666.6,  666.6,  666.6,  666.6],
       [ 666.6,  666.6,  666.6,  666.6,  666.6]])

In [37]:
np.full(shape = (3, 5), fill_value = 666)  # 用指定元素来初始化一个元组.写上了参数名

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [39]:
np.full(fill_value = 666.6, shape = (3, 5))  # 用指定元素来初始化一个元组.写上了参数名,参数顺序就不重要了

array([[ 666.6,  666.6,  666.6,  666.6,  666.6],
       [ 666.6,  666.6,  666.6,  666.6,  666.6],
       [ 666.6,  666.6,  666.6,  666.6,  666.6]])

# numpy.arange方法

In [41]:
[i for i in range(0, 20, 2)] # 三个参数依次为起点、终点(不含)、步长,步长不能为浮点数

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
np.arange(0, 20, 2) # 三个参数依次为起点、终点(不含)、步长

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
np.arange(0, 1, 0.2) # 个参数依次为起点、终点(不含)、步长,步长能为浮点数

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [48]:
np.arange(0, 10) # 默认步长是1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# numpy.linspace 方法 : 将区间等分

In [51]:
np.linspace(0, 20, 10) # 三个参数依次为起点、终点(不含)、要等分的份数(包含终止点，也算一份)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [53]:
np.linspace(0, 20, 11) # 三个参数依次为起点、终点(不含)、要等分的份数(包含终止点，也算一份)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

# numpy.random : 生成指定区间内的随机数(左闭右开)

In [58]:
np.random.randint(0, 10) # 生成0~10之间的随机整数,不包含10

0

In [65]:
np.random.randint(0, 10, 100) # 生成100个0~10之间的随机整数，不包含10

array([5, 0, 4, 5, 6, 4, 6, 0, 1, 9, 0, 6, 8, 1, 6, 0, 4, 3, 2, 4, 5, 7, 7,
       7, 9, 2, 5, 2, 1, 8, 8, 6, 2, 7, 2, 9, 7, 8, 2, 3, 6, 0, 1, 1, 9, 1,
       0, 9, 8, 1, 5, 2, 6, 2, 9, 2, 1, 3, 2, 8, 6, 1, 3, 1, 6, 4, 3, 2, 0,
       8, 0, 3, 3, 0, 3, 1, 1, 9, 4, 9, 7, 8, 5, 7, 2, 6, 1, 2, 9, 7, 3, 4,
       0, 4, 4, 4, 6, 9, 1, 3])

In [67]:
np.random.randint(4, 8, size = 66) # 生成66个4~8之间的随机整数，不包含8,指定size是为了提高可读性

array([6, 5, 5, 4, 7, 7, 5, 5, 6, 4, 5, 4, 5, 7, 5, 6, 5, 7, 5, 4, 6, 5, 6,
       7, 4, 4, 6, 7, 6, 5, 5, 5, 6, 4, 4, 6, 6, 5, 5, 7, 7, 4, 5, 5, 7, 6,
       4, 5, 4, 4, 7, 7, 7, 5, 6, 7, 7, 7, 7, 6, 6, 4, 4, 6, 4, 6])

In [69]:
np.random.randint(4, 8, size = (3, 5)) # 生成3行5列的4~8之间的随机整数，不包含8,指定size是为了提高可读性

array([[7, 4, 6, 4, 6],
       [7, 6, 5, 5, 5],
       [7, 4, 6, 6, 7]])

In [73]:
np.random.seed(666) # 显示地指定种子，相同种子每次生成的随机数(组是相同地)，可以在调试的时候设置下种子使得每次的随机输入都是相同地
np.random.randint(4, 8, size = (3, 5)) # 生成3行5列的4~8之间的随机整数，不包含8,指定size是为了提高可读性

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [76]:
np.random.random() # 默认的是生成浮点数,范围默认是0~1

0.2334009125847185

In [79]:
np.random.random(10) # 生成10个0~1的随机数

array([ 0.31581532,  0.39016259,  0.26832981,  0.75366384,  0.66673747,
        0.87287954,  0.52109719,  0.75020425,  0.32940234,  0.29130197])

In [82]:
np.random.random((3, 5)) # 生成3行5列的0~1之间的随机数

array([[ 0.35932938,  0.42014544,  0.2026436 ,  0.63279787,  0.18935861],
       [ 0.1308497 ,  0.75765845,  0.34158167,  0.52138487,  0.88302327],
       [ 0.44914216,  0.23902229,  0.33014086,  0.26650938,  0.79768204]])

In [86]:
np.random.random((3, 5)) # 生成3行5列的0~1之间的随机数

array([[ 0.63205157,  0.12168885,  0.27480879,  0.07770505,  0.15726591],
       [ 0.14978044,  0.38535367,  0.70941476,  0.44518764,  0.01584702],
       [ 0.99491381,  0.90632665,  0.05199571,  0.86100897,  0.51224649]])

In [92]:
np.random.normal() # 生成一个符合正太分布的随机数(均值为0，方差为1)

0.4625386762034723

In [95]:
np.random.normal(10, 100) # 生成一个符合正太分布的随机数(均值为10，方差为100)

-135.3113140149696

In [96]:
np.random.normal(10, 100, (3, 5)) # 生成一个符合正太分布的3行5列d随机矩阵(均值为10，方差为100)

array([[  73.64203022, -175.0816505 ,  150.63753176,   -6.79322375,
          61.00457098],
       [  52.70139876, -101.76085589,  125.94368288,   -3.7953426 ,
          75.04299113],
       [  14.23292326,  174.80307244,    4.34057675,  141.36560676,
          60.32695446]])